name: PR Stats

on:
  pull_request:
    types: [opened]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: nickmccomb/pull-request-stats@master
        with:
          period: 30
          charts: true
          sort-by: 'TIME'
          telemetry: false
