name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upgrade Yarn
        run: |
          corepack enable
          yarn set version stable

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - run: yarn install

      - run: yarn test
